apiVersion: v1
kind: Pod
metadata:
  name: allkeyvaluepairs-configmapdefinecontainerenvironment-variable
spec:
  containers:
    - name: allkeyvaluepairs-configmapdefinecontainerenvironment-container
      image: registry.k8s.io/busybox
      # command   Executed when the container starts
      # /bin/sh   Shell interpreter
      # -c        Flag to indicate that the following argument is a command
      # env       It's a command which typically prints the environment variables container
      command: [ "/bin/sh", "-c", "env" ]
      # envFrom     All configMap's data -> environment variable in the pod
      envFrom:
        - configMapRef:
            name: allkeyvalue-pairs
  restartPolicy: Never
