apiVersion: v1
kind: Node
metadata:
  name: my-node
  labels:
    my-custom-label: "example-value"  # Label matching the nodeSelector in RuntimeClass
spec:
  taints:
    - key: dedicated
      value: worker-3
      effect: NoSchedule
  unschedulable: false
  podCIDR: 192.168.1.0/24
  #providerID: my-cloud-provider://instance-id
# status is managed by Kubernetes
#status:
#  addresses:
#    - type: InternalIP
#      address: 192.168.1.10
#  conditions:
#    - type: Ready
#      status: "True"
#      lastHeartbeatTime: "2023-01-20T10:15:00Z"
#    - type: OutOfDisk
#      status: "False"
#    - type: MemoryPressure
#      status: "False"
#    - type: DiskPressure
#      status: "False"
#    - type: PIDPressure
#      status: "False"
#    - type: NetworkUnavailable
#      status: "False"
#  daemonEndpoints:
#    kubeletEndpoint:
#      Port: 10250
#  nodeInfo:
#    machineID: "my-machine-id"
#    systemUUID: "my-system-uuid"
#    bootID: "my-boot-id"
#    kernelVersion: "4.19.0-16-amd64"
#    osImage: "Ubuntu 18.04.3 LTS"
#    containerRuntimeVersion: "docker://19.3.1"
#    kubeletVersion: "v1.28.0"
#    kubeProxyVersion: "v1.28.0"
#    architecture: "arm64"
#    operatingSystem: "linux"


