apiVersion: v1
kind: Pod
metadata:
  name: pod-withadelay-updatingavolume-subpath
spec:
  containers:
    - name: container-withadelay-updatingavolume-subpath
      image: nginx
      volumeMounts:
        - name: volume-toupdate-subpath
          # mountPath     Path in which to mount the volume
          mountPath: /etc/config/app.properties
          subPath: app.properties
  volumes:
    - name: volume-toupdate-subpath
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: configmap-toupdate-subpath
  restartPolicy: Never
