# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#horizontalpodautoscaler-v1-autoscaling
apiVersion: autoscaling/v1    # v1 used to create it
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa-v1
spec:
  scaleTargetRef:
#    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
