# non-production-database-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: non-production-database
spec:
  clusterIP: None

---
# non-production-endpointslice.yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: non-production-database-slice
addressType: IPv4
# Add real IP addresses
endpoints:
  - addresses:
      #- non-production-db-pod-1-ip
      - "10.4.5.1"
  - addresses:
      #- non-production-db-pod-2-ip
      - "10.4.5.2"
ports:
  - name: database-port
    protocol: TCP
    port: 5432
