kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: other-na
  - role: worker
    labels:
      simple: true
      required.1/1.1: true
name: cluster-namingnode