apiVersion: v1
kind: Pod
metadata:
  # 1. Invalid number of characters
  #name: several-configmap-define-container-environment-variable
  name: several-configmapdefinecontainerenvironment-variable
spec:
  containers:
    - name: several-configmapdefinecontainerenvironmentvariablecontainer
      image: registry.k8s.io/busybox
      # command   Executed when the container starts
      # /bin/sh   Shell interpreter
      # -c        Flag to indicate that the following argument is a command
      # env       It's a command which typically prints the environment variables container
      command: [ "/bin/sh", "-c", "env" ]
      # Define the environment variable
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: log_level
  restartPolicy: Never
