apiVersion: v1
kind: Service
metadata:
  name: my-h2c-service
spec:
  selector:
    app: my-app
  ports:
    - name: h2c
      protocol: TCP
      port: 80
      targetPort: 8080
      appProtocol: "kubernetes.io/h2c"
