apiVersion: v1
kind: Service
metadata:
  name: my-udp-service
spec:
  selector:
    app: my-app
  ports:
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 1053
      appProtocol: udp
