apiVersion: v1
kind: Pod
metadata:
  name: invalid-env-pod
spec:
  containers:
    - name: my-container
      image: nginx
      # command   Executed when the container starts
      # /bin/sh   Shell interpreter
      # -c        Flag to indicate that the following argument is a command
      # env       It's a command which typically prints the environment variables container
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Next environment variable is invalid -> skipped and pod started
        - name: "Invalid-Variable-Name"  # Invalid variable name with uppercase characters
          value: "value"
        - name: SPECIAL_LEVEL
          value: very