# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # 1. LoadBalancer
  # If your cluster supports it
  # type: LoadBalancer
  # 2. ClusterIP
  # Default one if you don't specify anything
  ports:
  - port: 80
    # Service listening on this port
    # Incoming traffic on this port -> service forwards to -> pods with the next selectors on the same port
  selector:
    app: guestbook
    tier: frontend