# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  ports:
  - port: 6379
    # Service listening on this port
    # Incoming traffic on this port -> service forwards to -> pods with the next selectors on the same port
  selector:
    app: redis
    role: follower
    tier: backend