# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379            # Service is listening on service's ClusterIp:Port
    targetPort: 6379      # pod's ClusterIP:TargetPort
    # Pods are filtered by the next selectors
  selector:
    app: redis
    role: leader
    tier: backend