# https://kind.sigs.k8s.io/docs/user/configuration/#getting-started
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind-with-seccomp-profiles
nodes:
  # 1 node hosting the control plane
- role: control-plane
  # https://kind.sigs.k8s.io/docs/user/configuration/#getting-started
  extraMounts:
  - hostPath: "./profiles"
    containerPath: "/var/lib/kubelet/seccomp/profiles"