apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiversioning.example.com
spec:
  group: example.com
  names:
    kind: Multi
    plural: multiversioning
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                  enum:
                    - v1alpha1
                key1:
                  type: string
    - name: v1beta1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                  enum:
                    - v1beta1
                key1:
                  type: string
                newField:
                  type: string
  scope: Namespaced
