apiVersion: apiextensions.k8s.io/v1   # API Group / API Version used for creating the CRD
kind: CustomResourceDefinition
metadata:
  name: unsetorzeros.example.com
spec:
  group: example.com    # API group for the custom resource that we are creating
  names:    # Names used for the custom resource
    kind: unsetorzero
    plural: unsetorzeros
  scope: Namespaced
  versions:   # API versions for the custom resource that we are creating
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:    # Here you have got all OpenAPI's schema freedom to define it
          type: object
          properties:
            spec:
              type: object
              properties:
                key1:
                  type: string
                key2:
                  type: integer
                city:
                  type: string
                  default: "Madrid"   # Defaulting
          required:
            - spec
