apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: namespace-a  # Use your namespace or omit this line if not using a separate namespace
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
