apiVersion: v1
kind: Endpoints
metadata:
  name: invalid-endpoints-service-ipv4
subsets:
  - addresses:
      - ip: 127.0.0.1  # Invalid loopback address
    ports:
      - port: 8080

---
apiVersion: v1
kind: Endpoints
metadata:
  name: invalid-endpoints-service-ipv6
subsets:
  - addresses:
      - ip: ::1  # Invalid loopback address for service endpoints
    ports:
      - port: 8080
