apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Endpoints
metadata:
  name: invalid-endpoints-service
subsets:
  - addresses:
      - ip: 10.0.0.100  # This IP doesn't correspond to any pod
    ports:
      - port: 8080
