apiVersion: v1
kind: Service
metadata:
  name: simple-clusterip-service
spec:
  selector:   # Label selector for matching pods
    app: backend-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376    # match with the pod.spec.containers[x].ports.containerPort
  #clusterIP: 10.0.0.1    # Invalid value within the range
  clusterIP: 10.96.0.2

