kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    logging:
      format: "json"
      verbosity: 6
nodes:
  - role: control-plane
    image: kindest/node:v1.28.0
    # How to change controlPlane's name?
    # Attempt1:
#    kubeadmConfigPatches:
#      - |
#        kind: JoinConfiguration
#        nodeRegistration:
#          name: control
    # Solution: TODO:
  - role: worker
    image: kindest/node:v1.28.0
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: other-na
  - role: worker
    image: kindest/node:v1.28.0
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: other-node
name: cluster-tools-for-monitoring