apiVersion: v1
kind: Pod
metadata:
  name: podfields-viaenv
spec:
  containers:
    - name: container-viaenv
      image: busybox
      command: ["sh", "-c", "env"]
      env:
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NODE_PRIMARY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        # Next field must be enabled firstly
#        - name: POD_NODE_ALL_IPS
#          valueFrom:
#            fieldRef:
#              fieldPath: status.hostIPs
        - name: POD_PRIMARY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_ALL_IPS
          valueFrom:
            fieldRef:
              fieldPath: status.podIPs

