apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
    - name: my-app-container
      image: nginx:latest
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
