apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-status-readinessprobefail
spec:
  replicas: 3
  progressDeadlineSeconds: 10       # Seconds waited for the Deployment Controller to mark the Deployment as stuck
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'exit 1'  # Simulate a failure by exiting with a non-zero code
          ports:
            - containerPort: 80