kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.29.0
  - role: worker
    image: kindest/node:v1.29.0
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: other-na
  - role: worker
    image: kindest/node:v1.29.0
    labels:
      topologykey.1/1.1: "true"
      topologykey.1/1.2: "true"
featureGates:
  "MatchLabelKeysInPodAffinity": true
name: cluster-4