# namespace             -- Pod to match with namespace-1
apiVersion: v1
kind: Pod
metadata:
  name: namespace-1-1
  labels:
    interpod.1/1: "true"
    interpod.1/2: "true"
  namespace: interpod-namespace-2
spec:
  nodeSelector:       # Easiest to assign to a specific node
    topologykey.1/1.1: "true"
  containers:
    - name: namespace-1-1
      image: busybox:latest
      command:
        - sleep
        - "3600"

---
# namespaceSelector             -- Pod to match with namespaceselector-1
apiVersion: v1
kind: Pod
metadata:
  name: namespaceselector-1-1
  labels:
    interpod.1/1: "true"
    interpod.1/2: "true"
  namespace: interpod-namespaceselector-1
spec:
  nodeSelector:       # Easiest to assign to a specific node
    topologykey.1/1.1: "true"
  containers:
    - name: namespaceselector-1-1
      image: busybox:latest
      command:
        - sleep
        - "3600"


---
# matchLabelKeys             -- Pod to match with matchlabelkeys-1
apiVersion: v1
kind: Pod
metadata:
  name: matchlabelkeys-1-1
  labels:
    interpod.1/1: "true"
    interpod.1/2: "true"
    matchlabelkeys.1/1: "true"
spec:
  nodeSelector:       # Easiest to assign to a specific node
    topologykey.1/1.1: "true"
  containers:
    - name: matchlabelkeys-1-1
      image: busybox:latest
      command:
        - sleep
        - "3600"

