apiVersion: v1
kind: Pod
metadata:
  name: pod-passingenvironmentvariables-ascommand
spec:
  containers:
    - name: container-passingenvironmentvariables-ascommand
      image: registry.k8s.io/busybox
      # command   Executed when the container starts
      # /bin/echo      Command to echo
      # $(SPECIAL_LEVEL_KEY) $(SPECIAL_TYPE_KEY)        Arguments with the environment variables, to pass to the previous command
      command: [ "/bin/echo", "$(SPECIAL_LEVEL_KEY) $(SPECIAL_TYPE_KEY)" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: log_level
  restartPolicy: Never
