apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  #key: value
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  #key: value
  log_level: INFO