apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: namespace-b
spec:
  containers:
    - name: my-container
      image: nginx
      env:
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: key
