apiVersion: v1
kind: Pod
metadata:
  name: dummy
spec:
  containers:
    - name: dummy
      image: busybox:1.28
      command:
        - sleep
        - "3600"

---
# guaranteed
apiVersion: v1
kind: Pod
metadata:
  name: guaranteed
spec:
  containers:
    - name: guaranteed1
      image: busybox:1.28
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 10m
          memory: 10Mi
      command:
        - sleep
        - "3600"
    - name: guaranteed2
      image: nginx
      resources:
        limits:
          cpu: 150m
          memory: 10Mi
        requests:
          cpu: 150m
          memory: 10Mi


---
# burstable                 # NOT meet all Guaranteed's requirements
apiVersion: v1
kind: Pod
metadata:
  name: burstable-1
spec:
  containers:
    - name: burstable-1-1
      image: busybox:1.28
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 10m
          memory: 10Mi
      command:
        - sleep
        - "3600"
    - name: burstable-1-2
      image: nginx
      resources:
        limits:
          cpu: 150m
          memory: 20Mi    # Since in this container memory's limit != memory's request
        requests:
          cpu: 150m
          memory: 10Mi

---
# burstable                 # 1! container defining a resource
apiVersion: v1
kind: Pod
metadata:
  name: burstable-2
spec:
  containers:
    - name: burstable-2-1
      image: busybox:1.28
      command:
        - sleep
        - "3600"
    - name: burstable-2-2
      image: nginx
      resources:
        limits:
          cpu: 150m       # Unique resource defined in all pod's containers

---
# besteffort-1                  # none container has resource defined
apiVersion: v1
kind: Pod
metadata:
  name: besteffort-1
spec:
  containers:
    - name: besteffort-1-1
      image: busybox:1.28
      command:
        - sleep
        - "3600"
    - name: besteffort-1-2
      image: nginx

