apiVersion: v1
kind: Pod
metadata:
  name: podfields-bothfields-viadownwardvolumefiles
  annotations:
    description: "pod to expose via downwardAPI volume file"
    mechanisms: "both"
  labels:
    purpose: "best"
    environment: test
spec:
  volumes:
    - name: pod-info
      downwardAPI:
        items:
          - path: "metadata_name"
            fieldRef:
              fieldPath: metadata.name
          - path: "metadata_namespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "metadata_uid"
            fieldRef:
              fieldPath: metadata.uid
          - path: "metadata_annotation_description"
            fieldRef:
              fieldPath: metadata.annotations['description']
          - path: "metadata_label_purpose"
            fieldRef:
              fieldPath: metadata.labels['purpose']
  containers:
    - name: container-bothfields-viadownwardvolumefiles
      image: busybox
      command: ["sh", "-c", "cat /etc/pod_info/metadata_name && cat /etc/pod_info/metadata_namespace && cat /etc/pod_info/metadata_uid && cat /etc/pod_info/metadata_annotation_description && cat /etc/pod_info/metadata_label_purpose"]
      volumeMounts:
        - name: pod-info
          mountPath: /etc/pod_info
