apiVersion: v1
kind: Pod
metadata:
  name: networkingaddress1
  labels:
    pod: networkingaddress1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
