# TODO: clean notes
# This manifest mounts C:\Data\foo on the host as C:\foo, inside the
# single container that runs within the hostpath-example-windows Pod.
#
# The mount into the container is read-only.
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example-windows
spec:
  os: { name: windows }
  nodeSelector:
    kubernetes.io/os: windows
  containers:
    - name: example-container
      image: microsoft/windowsservercore:1709
      volumeMounts:
        - name: example-volume
          mountPath: "C:\\foo"
          readOnly: true
  volumes:
    # mount C:\Data\foo from the host, but only if that directory already exists
    - name: example-volume
      hostPath:
        path: "C:\\Data\\foo" # directory location on host
        type: Directory       # this field is optional