apiVersion: v1
kind: Pod
metadata:
  name: pod-directoryorcreate
spec:
  containers:
    - image: busybox:latest
      name: container-directoryorcreate
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
          readOnly: false
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /Users/dancer13/Pictures/directoryorcreate
        type: DirectoryOrCreate   # Create a directory with name defined in  "mountPath" on the container
