apiVersion: v1
kind: Pod
metadata:
  name: pod-fileorcreate
spec:
  containers:
    - image: busybox:latest
      name: container-fileorcreate
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /Users/dancer13/Pictures/fileorcreate
        type: FileOrCreate  # Create a file with name defined in "mountPath" on the container
