apiVersion: v1
kind: Pod
metadata:
  name: pod-socket
spec:
  containers:
    - image: busybox:latest
      name: container-socket
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /Users/dancer13/Pictures
        type: Socket # Check if a SOCKET with name defined in "mountPath" on the container
