apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-oldreplicasetscleanup
spec:
  replicas: 3
  revisionHistoryLimit: 2     # Establish the number of ReplicaSets to retain
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80