# Pod 1: Web App 1
apiVersion: v1
kind: Pod
metadata:
  name: web-app-1
  labels:
    app: my-app
    component: web
spec:
  containers:
    - name: web-app-container
      image: nginx:latest
      ports:
        - containerPort: 80

---

# Pod 2: Web App 2
apiVersion: v1
kind: Pod
metadata:
  name: web-app-2
  labels:
    app: my-app
    component: web
spec:
  containers:
    - name: web-app-container
      image: nginx:latest
      ports:
        - containerPort: 80
