# Service: my-app-service
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    component: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
