apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 81      # Port exposed by this Service
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service2
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80    # Port exposed by this Service
      # targetPort: 80      If you don't specify it -> it's assumed that targetPort = port!!!
  type: NodePort