apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: namespace-a
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Assuming your pods are listening on port 8080
