apiVersion: v1      # API Group / API Version   -- API Group is core, but no specified here
kind: Pod
metadata:
  name: nginx
  # 1. Fields which can not be updated!!!!
  #namespace: other
  #name: newname
  #uid: 222
  #deletionTimestamp: "222"

  # 2. if deletionTimestamp is set ->
  # deletionTimestamp: "2006-01-02T15:04:05Z"
  #finalizers:
    # - "aa"    TODO: How to add it?
spec:
  containers:
    - name: nginx
      # image: nginx:1.14.2
      image: nginx:1.14.1   # It can be updated
      ports:
        - containerPort: 80
  initContainers:     # Added new once pod exists, is not possible
    - name: busy
      image: busybox:1.22
  # activeDeadlineSeconds: 2
  # activeDeadlineSeconds: 5    Impossible to adjust increasing it
  activeDeadlineSeconds: 1
  tolerations:
    - key: example-key
      operator: Equal
      value: example-value
      effect: NoSchedule


