apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
spec:
  selector:
    matchLabels:
      app: pod-by-workloadresource-daemonset
  template:
    # This is the pod template
    metadata:
      labels:
        app: pod-by-workloadresource-daemonset
    spec:
      containers:
        - name: container-by-workloadresource-daemonset
          #image: nginx:latest
          image: nginx:stable
