apiVersion: core/v1      # API Group / API Version   WRONG specifying API Group here!!!
kind: Pod
metadata:
  name: specifyingAPIGroup
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
