apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  selector:   # Label selector for matching pods
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376    # match with the pod.spec.containers[x].ports.containerPort
  type: NodePort
