apiVersion: apiextensions.k8s.io/v1   # API Group / API Version used for creating the CRD
kind: CustomResourceDefinition
metadata:
  name: labelandannotations.example.com
  labels:             # Add labels as other built-in Kubernetes resources
    environment: test
    random: randomValue
  annotations:        # Add annotations as other built-in Kubernetes resources
    annotationFirst: "annotationFirstValue"
spec:
  group: example.com
  names:
    kind: labelandannotation
    plural: labelandannotations
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            first:
              type: string

