apiVersion: v1
kind: Pod
metadata:
  name: audit-pod
  labels:
    app: audit-pod
spec:
  securityContext:
    seccompProfile:
      # https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L3531
      type: Localhost
      localhostProfile: profiles/audit.json
  containers:
  - name: test-container
    image: hashicorp/http-echo:1.0
    args:
    - "-text=just made some syscalls!"
    securityContext:
      # Let, if the container running in a pod is allowed to change its own process privilege
      allowPrivilegeEscalation: false