apiVersion: v1
kind: Pod
metadata:
  name: default-pod
  labels:
    app: default-pod
spec:
  # Set for all the pod's containers
  securityContext:
    seccompProfile:
      # https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L3529
      type: RuntimeDefault
  containers:
  - name: test-container
    image: hashicorp/http-echo:1.0
    args:
    - "-text=just made some more syscalls!"
    securityContext:
      # Let, if the container running in a pod is allowed to change its own process privilege
      allowPrivilegeEscalation: false