apiVersion: v1
kind: Pod
metadata:
  name: violation-pod
  labels:
    app: violation-pod
spec:
  securityContext:
    seccompProfile:
      # https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L3531
      type: Localhost
      localhostProfile: profiles/violation.json
  containers:
  - name: test-container
    image: hashicorp/http-echo:1.0
    args:
    - "-text=just made some syscalls!"
    securityContext:
      # Let, if the container running in a pod is allowed to change its own process privilege
      allowPrivilegeEscalation: false