apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace  # Use your namespace or omit this line if not using a separate namespace
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
