apiVersion: apiextensions.k8s.io/v1   # API Group / API Version used for creating the CRD
kind: CustomResourceDefinition
metadata:
  name: myapps.example.com
spec:
  group: example.com    # API group for the custom resource that we are creating
  names:    # Names used for the custom resource
    kind: MyApp
    plural: myapps
  scope: Namespaced   # Instance belongs to a specific namespace -- TODO: Why isn't it assigned to anything?
  versions:   # API versions for the custom resource that we are creating
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:    # Here you have got all OpenAPI's schema freedom to define it
          type: object
          properties:
            spec:
              type: object
              properties:
                version:      # Way to handle the version!! TODO: Isn't there another way without adding a property?
                  type: string
                  enum:
                    - v1
                key1:
                  type: string
                key2:
                  type: integer
                country:
                  type: string
                  enum:
                    - Spain
                    - Germany
                    - Netherlands
                    - Italy
                city:
                  type: string
                  default: "Madrid"   # Defaulting
          required:
            - spec
    - name: v2        # Another version to use
      served: true
      # storage: true   # Invalid to have several versions marked as storage true!!!!!
      storage: false
      schema:
        openAPIV3Schema: # Here you have got all OpenAPI's schema freedom to define it
          type: object
          properties:
            spec:
              type: object
              properties:
                version:    # Way to handle the version!! TODO: Isn't there another way without adding a property?
                  type: string
                  enum:
                    - v2
                key1:
                  type: string
                key2:
                  type: integer
                country:
                  type: string
                  enum:
                    - Spain
                    - Germany
                    - Netherlands
                    - Italy
                city:
                  type: string
                  default: "Madrid"   # Defaulting
                newField:
                  type: string
          required:
            - spec


