# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    other: frontend-service
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8080
  type: NodePort
