apiVersion: v1
kind: Pod
metadata:
  name: pod-multivolume
spec:
  containers:
    - name: container-multivolume
      #image: nginx:latest
      image: nginx:stable   # Update the pod, updating the tag
      # command: ["sleep", "60"]    # Forbidden to update the pod with this change, once the pod is running
      # Where to mount the volumes into each container
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: data-volume
          mountPath: /var/data
        - name: temp-volume
          mountPath: /tmp
  # volumes to provide
  # Several of different type are provided
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map
    - name: data-volume
      persistentVolumeClaim:
        claimName: my-pvc   # specify the name of the PV, that the PVC should claim storage from
    - name: temp-volume
      emptyDir: {}
