apiVersion: v1
kind: Service
metadata:
  name: headlessservice-withselectors
spec:
  clusterIP: None   # Indicating that there are Headless Service
  # Selectors to route traffic to certain pods
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
