apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir-specified
spec:
  volumes:
    - name: emptydir-volume-default
      emptyDir: {}
      # medium not specified -> medium which backs the node, that locally is nothing?
    - name: emptydir-volume-specified
      emptyDir:
        # customization
        sizeLimit: 500Mi
        medium: "Memory"
  containers:
    - name: container-emptydir-specified
      image: nginx:latest
      volumeMounts:
        - mountPath: /data/empty
          name: emptydir-volume-default
        - mountPath: /data/content
          name: emptydir-volume-specified
      command:
        - sh
        - -c
        - ls /data/empty && ls /data/content
    - name: container-emptydir-specified-two
      image: nginx:latest
      # Same volumes can be shared by other pod's containers, being mounted in each one in different paths
      volumeMounts:
        - mountPath: /data/emptytwo
          name: emptydir-volume-default
        - mountPath: /data/contenttwo
          name: emptydir-volume-specified
