apiVersion: v1
kind: Pod
metadata:
  name: nodeselector
spec:
  nodeSelector:
    simple: "true"
  containers:
    - name: nodeselector
      image: busybox:latest
      command:
        - sleep
        - "3600"


