apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      #name: http   # Invalid to comment it
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      #name: https   # Invalid to comment it
      name: https
      port: 443
      targetPort: 8443
